# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/arjunmallay/riscv-master/riscv-org/riscv-org.cache/wt [current_project]
set_property parent.project_path /home/arjunmallay/riscv-master/riscv-org/riscv-org.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/arjunmallay/riscv-master/riscv-org/riscv-org.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/MemoryUartDumper.v
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/instruction_memory.v
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/memory.v
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/performancecounter.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_defs.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_alu.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_core.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_csr.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_csr_regfile.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_decode.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_decoder.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_divider.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_exec.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_fetch.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_issue.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_lsu.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_mmu.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_multiplier.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_pipe_ctrl.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_regfile.v
  /home/arjunmallay/riscv-master/core/riscv/riscv_xilinx_2r1w.v
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/uart_tx.v
  /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/new/riscv_soc_top.v
}
read_ip -quiet /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/constrs_1/new/nexysconstraints.xdc
set_property used_in_implementation false [get_files /home/arjunmallay/riscv-master/riscv-org/riscv-org.srcs/constrs_1/new/nexysconstraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
